// Generated by gencpp from file mtf_bridge/Patch.msg
// DO NOT EDIT!


#ifndef MTF_BRIDGE_MESSAGE_PATCH_H
#define MTF_BRIDGE_MESSAGE_PATCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mtf_bridge/Point.h>
#include <mtf_bridge/Point.h>

namespace mtf_bridge
{
template <class ContainerAllocator>
struct Patch_
{
  typedef Patch_<ContainerAllocator> Type;

  Patch_()
    : corners()
    , center()  {
    }
  Patch_(const ContainerAllocator& _alloc)
    : corners()
    , center(_alloc)  {
      corners.assign( ::mtf_bridge::Point_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::mtf_bridge::Point_<ContainerAllocator> , 4>  _corners_type;
  _corners_type corners;

   typedef  ::mtf_bridge::Point_<ContainerAllocator>  _center_type;
  _center_type center;




  typedef boost::shared_ptr< ::mtf_bridge::Patch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mtf_bridge::Patch_<ContainerAllocator> const> ConstPtr;

}; // struct Patch_

typedef ::mtf_bridge::Patch_<std::allocator<void> > Patch;

typedef boost::shared_ptr< ::mtf_bridge::Patch > PatchPtr;
typedef boost::shared_ptr< ::mtf_bridge::Patch const> PatchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mtf_bridge::Patch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mtf_bridge::Patch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mtf_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mtf_bridge': ['/home/abhineet/E/UofA/Thesis/Code/TrackingFramework/C++/MTF/ROS/src/mtf_bridge/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mtf_bridge::Patch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mtf_bridge::Patch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mtf_bridge::Patch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mtf_bridge::Patch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mtf_bridge::Patch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mtf_bridge::Patch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mtf_bridge::Patch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fe35727486600b70962648847a432de";
  }

  static const char* value(const ::mtf_bridge::Patch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fe35727486600b7ULL;
  static const uint64_t static_value2 = 0x0962648847a432deULL;
};

template<class ContainerAllocator>
struct DataType< ::mtf_bridge::Patch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mtf_bridge/Patch";
  }

  static const char* value(const ::mtf_bridge::Patch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mtf_bridge::Patch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point[4] corners\n\
Point center\n\
\n\
================================================================================\n\
MSG: mtf_bridge/Point\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::mtf_bridge::Patch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mtf_bridge::Patch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.corners);
      stream.next(m.center);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Patch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mtf_bridge::Patch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mtf_bridge::Patch_<ContainerAllocator>& v)
  {
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mtf_bridge::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.corners[i]);
    }
    s << indent << "center: ";
    s << std::endl;
    Printer< ::mtf_bridge::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MTF_BRIDGE_MESSAGE_PATCH_H
