"""autogenerated by genpy from mtf_bridge/Patch.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mtf_bridge.msg

class Patch(genpy.Message):
  _md5sum = "1fe35727486600b70962648847a432de"
  _type = "mtf_bridge/Patch"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Point[4] corners
Point center

================================================================================
MSG: mtf_bridge/Point
float64 x
float64 y

"""
  __slots__ = ['corners','center']
  _slot_types = ['mtf_bridge/Point[4]','mtf_bridge/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       corners,center

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Patch, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.corners is None:
        self.corners = [mtf_bridge.msg.Point(),mtf_bridge.msg.Point(),mtf_bridge.msg.Point(),mtf_bridge.msg.Point()]
      if self.center is None:
        self.center = mtf_bridge.msg.Point()
    else:
      self.corners = [mtf_bridge.msg.Point(),mtf_bridge.msg.Point(),mtf_bridge.msg.Point(),mtf_bridge.msg.Point()]
      self.center = mtf_bridge.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      for val1 in self.corners:
        _x = val1
        buff.write(_struct_2d.pack(_x.x, _x.y))
      _x = self
      buff.write(_struct_2d.pack(_x.center.x, _x.center.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.corners is None:
        self.corners = None
      if self.center is None:
        self.center = mtf_bridge.msg.Point()
      end = 0
      self.corners = []
      for i in range(0, 4):
        val1 = mtf_bridge.msg.Point()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2d.unpack(str[start:end])
        self.corners.append(val1)
      _x = self
      start = end
      end += 16
      (_x.center.x, _x.center.y,) = _struct_2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      for val1 in self.corners:
        _x = val1
        buff.write(_struct_2d.pack(_x.x, _x.y))
      _x = self
      buff.write(_struct_2d.pack(_x.center.x, _x.center.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.corners is None:
        self.corners = None
      if self.center is None:
        self.center = mtf_bridge.msg.Point()
      end = 0
      self.corners = []
      for i in range(0, 4):
        val1 = mtf_bridge.msg.Point()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2d.unpack(str[start:end])
        self.corners.append(val1)
      _x = self
      start = end
      end += 16
      (_x.center.x, _x.center.y,) = _struct_2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d = struct.Struct("<2d")
