option(WITH_TEMPLATED "Enable templated implementations of search methods (faster at runtime but take much longer to compile)" ON)
option(WITH_GRID_TRACKERS "Enable Grid (RANSAC) trackers and RKLT" ON)
option(WITH_FEAT "Enable Feature based Tracker (requires nonfree OpenCV module)" ON)
option(WITH_REGNET "Enable regression network search method (requires a custom version of Caffe to be present)" OFF)

set(SEARCH_METHODS "")
set(SEARCH_METHODS_NT ESM AESM FCLK ICLK FALK IALK FCSD PF NN GridTrackerFlow)
set(SEARCH_PARAMS FCLK ICLK FALK IALK ESM NN PF Cascade Parallel Pyramidal RKLT GridTrackerFlow)
set(COMPOSITE_SEARCH_METHODS CascadeTracker ParallelTracker PyramidalTracker LineTracker)
if(WITH_TEMPLATED)
set(SEARCH_METHODS ${SEARCH_METHODS} ESM FCLK ICLK FALK IALK PF GNN)
set(COMPOSITE_SEARCH_METHODS ${COMPOSITE_SEARCH_METHODS} PyramidalSM ParallelSM CascadeSM)
else(WITH_TEMPLATED)
message(STATUS "Templated implementations of SMs are disabled")
set(MTF_DEFINITIONS ${MTF_DEFINITIONS} ENABLE_ONLY_NT)
endif()
if(WITH_GRID_TRACKERS)
	set(COMPOSITE_SEARCH_METHODS ${COMPOSITE_SEARCH_METHODS} GridTracker GridTrackerCV GridTrackerFlow RKLT)
	set(SEARCH_METHODS_NT ${SEARCH_METHODS_NT} RKLT)
endif(WITH_GRID_TRACKERS)
if(WITH_FEAT)		
	# message(STATUS "OpenCV_LIBRARIES: ${OpenCV_LIBRARIES}")
	findSubPart("${OpenCV_LIBRARIES}" "opencv_nonfree" CV_NONFREE_FOUND)
	# message(STATUS "CV_NONFREE_FOUND: ${CV_NONFREE_FOUND}")
	if(CV_NONFREE_FOUND)
		set(COMPOSITE_SEARCH_METHODS ${COMPOSITE_SEARCH_METHODS} FeatureTracker)
	else(CV_NONFREE_FOUND)
		message(STATUS "OpenCV nonfree module not found so disabling the feature based grid tracker")			
		set(MTF_DEFINITIONS ${MTF_DEFINITIONS} DISABLE_GRID_FEAT)
	endif(CV_NONFREE_FOUND)
else(WITH_FEAT)
	message(STATUS "Feature based grid tracker disabled")
	set(MTF_DEFINITIONS ${MTF_DEFINITIONS} DISABLE_GRID_FEAT)
endif(WITH_FEAT)
if(WITH_REGNET)
	set(SEARCH_METHODS_NT ${SEARCH_METHODS_NT} RegNet)
else(WITH_REGNET)
	message(STATUS "RegNet disabled")
	set(MTF_DEFINITIONS ${MTF_DEFINITIONS} DISABLE_REGNET)
endif(WITH_REGNET)

find_package(FLANN)
find_package(HDF5)
if(FLANN_FOUND AND HDF5_FOUND) 
set(SEARCH_METHODS ${SEARCH_METHODS} NN FGNN)
set(SEARCH_PARAMS ${SEARCH_PARAMS} FLANN)
set(MTF_LIBS ${MTF_LIBS} ${FLANN_LIBS} ${HDF5_LIBRARIES})
else()
message(STATUS "FLANN/HDF5 library not found so the templated version NN search method has been disabled")
set(MTF_DEFINITIONS ${MTF_DEFINITIONS} DISABLE_NN)
set(SEARCH_PARAMS ${SEARCH_PARAMS} FLANNCV)
endif()
set(SEARCH_METHODS ${SEARCH_METHODS} ${COMPOSITE_SEARCH_METHODS})

addPrefix("${SEARCH_METHODS_NT}" "NT/" SEARCH_METHODS_NT)
set(SEARCH_METHODS ${SEARCH_METHODS} ${SEARCH_METHODS_NT})

addPrefixAndSuffix("${SEARCH_METHODS}" "SM/src/" ".cc" SEARCH_METHODS_SRC)
addPrefixAndSuffix("${SEARCH_PARAMS}" "SM/src/" "Params.cc" SEARCH_PARAMS_SRC)

set(MTF_SRC ${MTF_SRC} ${SEARCH_METHODS_SRC} ${SEARCH_PARAMS_SRC})
set(MTF_INCLUDE_DIRS ${MTF_INCLUDE_DIRS} SM/include)
